// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="FileCopyCommand.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

// DO NOT MODIFY THIS FILE DIRECTLY. It is autogenerated from CommandImplementationTemplate.tt.

namespace WindowsSettingsClone.Shared.Commands
{
    using System.Collections.Generic;
    using CommandBridge;
    using Diagnostics;
    using ServiceContracts.CommandBridge;
    using ServiceContracts.Commands;

    /// <summary>
    /// Command that copies a file.
    /// </summary>
    public sealed class FileCopyCommand : ServiceCommand, IFileCopyCommand
    {
        //// ===========================================================================================================
        //// Constructors
        //// ===========================================================================================================

        public FileCopyCommand(string sourcePath, string destinationPath, bool overwrite)
            : base(ServiceCommandName.FileCopy)
        {
            SourcePath = Param.VerifyString(sourcePath, nameof(sourcePath));
            DestinationPath = Param.VerifyString(destinationPath, nameof(destinationPath));
            Overwrite = overwrite;
        }

        internal FileCopyCommand(BridgeMessageDeserializer deserializer)
            : base(ServiceCommandName.FileCopy)
        {
            SourcePath = deserializer.GetStringValue(ParamName.SourcePath);
            DestinationPath = deserializer.GetStringValue(ParamName.DestinationPath);
            Overwrite = deserializer.GetBoolValue(ParamName.Overwrite);
        }

        //// ===========================================================================================================
        //// Properties
        //// ===========================================================================================================

        public string SourcePath { get; }
        public string DestinationPath { get; }
        public bool Overwrite { get; }

        //// ===========================================================================================================
        //// Methods
        //// ===========================================================================================================

        internal override void SerializeParams(IDictionary<ParamName, object> valueSet)
        {
            valueSet.Add(ParamName.SourcePath, SourcePath);
            valueSet.Add(ParamName.DestinationPath, DestinationPath);
            valueSet.Add(ParamName.Overwrite, Overwrite);
        }
    }
}
