// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="SystemParametersInfoSetValueCommand.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

// DO NOT MODIFY THIS FILE DIRECTLY. It is autogenerated from CommandImplementationTemplate.tt.

namespace WindowsSettingsClone.Shared.Commands
{
    using System.Collections.Generic;
    using CommandBridge;
    using Diagnostics;
    using ServiceContracts.CommandBridge;
    using ServiceContracts.Commands;

    /// <summary>
    /// Command that invokes the underlying Win32 <c>SystemParametersInfo</c> function that sets a value.
    /// </summary>
    public sealed class SystemParametersInfoSetValueCommand : ServiceCommand, ISystemParametersInfoSetValueCommand
    {
        //// ===========================================================================================================
        //// Constructors
        //// ===========================================================================================================

        public SystemParametersInfoSetValueCommand(SystemParameterInfoKind systemParameter, SystemParameterInfoUpdateKind updateKind)
            : base(ServiceCommandName.SystemParametersInfoSetValue)
        {
            SystemParameter = systemParameter;
            UpdateKind = updateKind;
        }

        internal SystemParametersInfoSetValueCommand(BridgeMessageDeserializer deserializer)
            : base(ServiceCommandName.SystemParametersInfoSetValue)
        {
            SystemParameter = deserializer.GetEnumValue<SystemParameterInfoKind>(ParamName.SystemParameter);
            UpdateKind = deserializer.GetEnumValue<SystemParameterInfoUpdateKind>(ParamName.UpdateKind);
        }

        //// ===========================================================================================================
        //// Properties
        //// ===========================================================================================================

        public SystemParameterInfoKind SystemParameter { get; }
        public SystemParameterInfoUpdateKind UpdateKind { get; }

        //// ===========================================================================================================
        //// Methods
        //// ===========================================================================================================

        internal override void SerializeParams(IDictionary<ParamName, object> valueSet)
        {
            valueSet.Add(ParamName.SystemParameter, SystemParameter.ToString());
            valueSet.Add(ParamName.UpdateKind, UpdateKind.ToString());
        }
    }
}
