// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="SystemParametersInfoGetValueCommand.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

// DO NOT MODIFY THIS FILE DIRECTLY. It is autogenerated from CommandImplementationTemplate.tt.

namespace WindowsSettingsClone.Shared.Commands
{
    using System.Collections.Generic;
    using CommandBridge;
    using Diagnostics;
    using ServiceContracts.CommandBridge;
    using ServiceContracts.Commands;

    /// <summary>
    /// Command that invokes the underlying Win32 <c>SystemParametersInfo</c> function that retrieves a value.
    /// </summary>
    public sealed class SystemParametersInfoGetValueCommand : ServiceCommand, ISystemParametersInfoGetValueCommand
    {
        //// ===========================================================================================================
        //// Constructors
        //// ===========================================================================================================

        public SystemParametersInfoGetValueCommand(SystemParameterInfoKind systemParameter)
            : base(ServiceCommandName.SystemParametersInfoGetValue)
        {
            SystemParameter = systemParameter;
        }

        internal SystemParametersInfoGetValueCommand(BridgeMessageDeserializer deserializer)
            : base(ServiceCommandName.SystemParametersInfoGetValue)
        {
            SystemParameter = deserializer.GetEnumValue<SystemParameterInfoKind>(ParamName.SystemParameter);
        }

        //// ===========================================================================================================
        //// Properties
        //// ===========================================================================================================

        public SystemParameterInfoKind SystemParameter { get; }

        //// ===========================================================================================================
        //// Methods
        //// ===========================================================================================================

        internal override void SerializeParams(IDictionary<ParamName, object> valueSet)
        {
            valueSet.Add(ParamName.SystemParameter, SystemParameter.ToString());
        }
    }
}
