// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="ParamName.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

// DO NOT MODIFY THIS FILE DIRECTLY. It is autogenerated from ParamName.tt.

namespace WindowsSettingsClone.Shared.CommandBridge
{
    /// <summary>
    /// Contains all of the parameter names (keys) used in a serialized parameter bag (ValueSet).
    /// </summary>
    internal enum ParamName
    {
        BaseKey,
        CommandName,
        CommandResult,
        DefaultValue,
        EchoMessage,
        ErrorCode,
        ErrorMessage,
        Key,
        SystemParameter,
        UpdateKind,
        Value,
        ValueName,
    }
}
