// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="IRegistryReadIntValueCommand.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

// DO NOT MODIFY THIS FILE DIRECTLY. It is autogenerated from CommandInterfaces.tt.

namespace WindowsSettingsClone.ServiceContracts.Commands
{
    using CommandBridge;

    /// <summary>
    /// Command that reads an integer value (REG_DWORD) from the Windows Registry.
    /// </summary>
    public interface IRegistryReadIntValueCommand : IServiceCommand
    {
        RegistryBaseKey BaseKey { get; }
        string Key { get; }
        string ValueName { get; }
        int DefaultValue { get; }
    }
}
