// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="IRegistryWriteStringValueCommand.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

// DO NOT MODIFY THIS FILE DIRECTLY. It is autogenerated from CommandInterfaces.tt.

namespace WindowsSettingsClone.ServiceContracts.Commands
{
    using CommandBridge;

    /// <summary>
    /// Command that writes a string value (REG_SZ) to the Windows Registry.
    /// </summary>
    public interface IRegistryWriteStringValueCommand : IServiceCommand
    {
        RegistryBaseKey BaseKey { get; }
        string Key { get; }
        string ValueName { get; }
        string Value { get; }
    }
}
