// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="ServiceCommandName.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// <auto-generated/>
// ---------------------------------------------------------------------------------------------------------------------

// DO NOT MODIFY THIS FILE DIRECTLY. It is autogenerated from ServiceCommandName.tt.

namespace WindowsSettingsClone.ServiceContracts.CommandBridge
{
    /// <summary>
    /// Enumerates all of the service commands.
    /// </summary>
    public enum ServiceCommandName
    {
        // Keep this first
        Unknown,

        Echo,
        RegistryReadIntValue,
        RegistryReadStringValue,
        RegistryWriteIntValue,
        RegistryWriteStringValue,
        ShutdownServer,
        SystemParametersInfoGetValue,
        SystemParametersInfoSetValue,
    }
}
