//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsSettingsClone.Uwp.ViewModels {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsSettingsClone.Uwp.ViewModels.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutSettingName {
            get {
                return ResourceManager.GetString("AboutSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access work or school.
        /// </summary>
        internal static string AccessWorkOrSchoolSettingName {
            get {
                return ResourceManager.GetString("AccessWorkOrSchoolSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info.
        /// </summary>
        internal static string AccountInfoSettingName {
            get {
                return ResourceManager.GetString("AccountInfoSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your accounts, email, sync, work, family.
        /// </summary>
        internal static string AccountsGroupDescription {
            get {
                return ResourceManager.GetString("AccountsGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string AccountsGroupName {
            get {
                return ResourceManager.GetString("AccountsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation.
        /// </summary>
        internal static string ActivationSettingName {
            get {
                return ResourceManager.GetString("ActivationSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity history.
        /// </summary>
        internal static string ActivityHistorySettingName {
            get {
                return ResourceManager.GetString("ActivityHistorySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App diagnostics.
        /// </summary>
        internal static string AppDiagnosticsSettingName {
            get {
                return ResourceManager.GetString("AppDiagnosticsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App permissions.
        /// </summary>
        internal static string AppPermissionsSettingHeader {
            get {
                return ResourceManager.GetString("AppPermissionsSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps &amp; features.
        /// </summary>
        internal static string AppsAndFeaturesSettingName {
            get {
                return ResourceManager.GetString("AppsAndFeaturesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps for websites.
        /// </summary>
        internal static string AppsForWebsitesSettingName {
            get {
                return ResourceManager.GetString("AppsForWebsitesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall, defaults, optional features.
        /// </summary>
        internal static string AppsGroupDescription {
            get {
                return ResourceManager.GetString("AppsGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string AppsGroupName {
            get {
                return ResourceManager.GetString("AppsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string AudioSettingName {
            get {
                return ResourceManager.GetString("AudioSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic file downloads.
        /// </summary>
        internal static string AutomaticFileDownloadsSettingName {
            get {
                return ResourceManager.GetString("AutomaticFileDownloadsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPlay.
        /// </summary>
        internal static string AutoPlaySettingName {
            get {
                return ResourceManager.GetString("AutoPlaySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background apps.
        /// </summary>
        internal static string BackgroundAppsSettingName {
            get {
                return ResourceManager.GetString("BackgroundAppsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        internal static string BackgroundChangePictureIntervalComboBox10MinutesOption {
            get {
                return ResourceManager.GetString("BackgroundChangePictureIntervalComboBox10MinutesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        internal static string BackgroundChangePictureIntervalComboBox1DayOption {
            get {
                return ResourceManager.GetString("BackgroundChangePictureIntervalComboBox1DayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string BackgroundChangePictureIntervalComboBox1HourOption {
            get {
                return ResourceManager.GetString("BackgroundChangePictureIntervalComboBox1HourOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        internal static string BackgroundChangePictureIntervalComboBox1MinuteOption {
            get {
                return ResourceManager.GetString("BackgroundChangePictureIntervalComboBox1MinuteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string BackgroundChangePictureIntervalComboBox30MinutesOption {
            get {
                return ResourceManager.GetString("BackgroundChangePictureIntervalComboBox30MinutesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 hours.
        /// </summary>
        internal static string BackgroundChangePictureIntervalComboBox6HoursOption {
            get {
                return ResourceManager.GetString("BackgroundChangePictureIntervalComboBox6HoursOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string BackgroundComboBoxPictureOption {
            get {
                return ResourceManager.GetString("BackgroundComboBoxPictureOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        internal static string BackgroundComboBoxSlideshowOption {
            get {
                return ResourceManager.GetString("BackgroundComboBoxSlideshowOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid color.
        /// </summary>
        internal static string BackgroundComboBoxSolidColorOption {
            get {
                return ResourceManager.GetString("BackgroundComboBoxSolidColorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string BackgroundFitComboBoxCenterOption {
            get {
                return ResourceManager.GetString("BackgroundFitComboBoxCenterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string BackgroundFitComboBoxFillOption {
            get {
                return ResourceManager.GetString("BackgroundFitComboBoxFillOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        internal static string BackgroundFitComboBoxFitOption {
            get {
                return ResourceManager.GetString("BackgroundFitComboBoxFitOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        internal static string BackgroundFitComboBoxSpanOption {
            get {
                return ResourceManager.GetString("BackgroundFitComboBoxSpanOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string BackgroundFitComboBoxStretchOption {
            get {
                return ResourceManager.GetString("BackgroundFitComboBoxStretchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        internal static string BackgroundFitComboBoxTileOption {
            get {
                return ResourceManager.GetString("BackgroundFitComboBoxTileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string BackgroundSettingName {
            get {
                return ResourceManager.GetString("BackgroundSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupSettingName {
            get {
                return ResourceManager.GetString("BackupSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth &amp; other devices.
        /// </summary>
        internal static string BluetoothAndOtherDevicesSettingName {
            get {
                return ResourceManager.GetString("BluetoothAndOtherDevicesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcasting.
        /// </summary>
        internal static string BroadcastingSettingName {
            get {
                return ResourceManager.GetString("BroadcastingSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarSettingName {
            get {
                return ResourceManager.GetString("CalendarSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call history.
        /// </summary>
        internal static string CallHistorySettingName {
            get {
                return ResourceManager.GetString("CallHistorySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string CameraSettingName {
            get {
                return ResourceManager.GetString("CameraSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captures.
        /// </summary>
        internal static string CapturesSettingName {
            get {
                return ResourceManager.GetString("CapturesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string ClipboardSettingName {
            get {
                return ResourceManager.GetString("ClipboardSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed captions.
        /// </summary>
        internal static string ClosedCaptionsSettingName {
            get {
                return ResourceManager.GetString("ClosedCaptionsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color filters.
        /// </summary>
        internal static string ColorFiltersSettingName {
            get {
                return ResourceManager.GetString("ColorFiltersSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string ColorsSettingName {
            get {
                return ResourceManager.GetString("ColorsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ContactsSettingName {
            get {
                return ResourceManager.GetString("ContactsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortana language, permissions, notifications.
        /// </summary>
        internal static string CortanaGroupDescription {
            get {
                return ResourceManager.GetString("CortanaGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortana.
        /// </summary>
        internal static string CortanaGroupName {
            get {
                return ResourceManager.GetString("CortanaGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor &amp; pointer.
        /// </summary>
        internal static string CursorAndPointerSettingName {
            get {
                return ResourceManager.GetString("CursorAndPointerSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data usage.
        /// </summary>
        internal static string DataUsageSettingName {
            get {
                return ResourceManager.GetString("DataUsageSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; time.
        /// </summary>
        internal static string DateAndTimeSettingName {
            get {
                return ResourceManager.GetString("DateAndTimeSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default apps.
        /// </summary>
        internal static string DefaultAppsSettingName {
            get {
                return ResourceManager.GetString("DefaultAppsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Optimization.
        /// </summary>
        internal static string DeliveryOptimizationSettingName {
            get {
                return ResourceManager.GetString("DeliveryOptimizationSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth, printers, mouse.
        /// </summary>
        internal static string DevicesGroupDescription {
            get {
                return ResourceManager.GetString("DevicesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string DevicesGroupName {
            get {
                return ResourceManager.GetString("DevicesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics &amp; feedback.
        /// </summary>
        internal static string DiagnosticsAndFeedbackSettingName {
            get {
                return ResourceManager.GetString("DiagnosticsAndFeedbackSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial-up.
        /// </summary>
        internal static string DialUpSettingName {
            get {
                return ResourceManager.GetString("DialUpSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string DisplaySettingName {
            get {
                return ResourceManager.GetString("DisplaySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string DocumentsSettingName {
            get {
                return ResourceManager.GetString("DocumentsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrator, magnifier, high contrast.
        /// </summary>
        internal static string EaseOfAccessGroupDescription {
            get {
                return ResourceManager.GetString("EaseOfAccessGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of Access.
        /// </summary>
        internal static string EaseOfAccessGroupName {
            get {
                return ResourceManager.GetString("EaseOfAccessGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &amp; accounts.
        /// </summary>
        internal static string EmailAndAccountsSettingName {
            get {
                return ResourceManager.GetString("EmailAndAccountsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailSettingName {
            get {
                return ResourceManager.GetString("EmailSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet.
        /// </summary>
        internal static string EthernetSettingName {
            get {
                return ResourceManager.GetString("EthernetSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye control.
        /// </summary>
        internal static string EyeControlSettingName {
            get {
                return ResourceManager.GetString("EyeControlSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family &amp; other users.
        /// </summary>
        internal static string FamilyAndOtherUsersSettingName {
            get {
                return ResourceManager.GetString("FamilyAndOtherUsersSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system.
        /// </summary>
        internal static string FileSystemSettingName {
            get {
                return ResourceManager.GetString("FileSystemSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my device.
        /// </summary>
        internal static string FindMyDeviceSettingName {
            get {
                return ResourceManager.GetString("FindMyDeviceSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus assist.
        /// </summary>
        internal static string FocusAssistSettingName {
            get {
                return ResourceManager.GetString("FocusAssistSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string FontsSettingName {
            get {
                return ResourceManager.GetString("FontsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For developers.
        /// </summary>
        internal static string ForDevelopersSettingName {
            get {
                return ResourceManager.GetString("ForDevelopersSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game bar.
        /// </summary>
        internal static string GameBarSettingName {
            get {
                return ResourceManager.GetString("GameBarSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mode.
        /// </summary>
        internal static string GameModeSettingName {
            get {
                return ResourceManager.GetString("GameModeSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game bar, captures, broadcasting, Game Mode.
        /// </summary>
        internal static string GamingGroupDescription {
            get {
                return ResourceManager.GetString("GamingGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming.
        /// </summary>
        internal static string GamingGroupName {
            get {
                return ResourceManager.GetString("GamingGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralSettingName {
            get {
                return ResourceManager.GetString("GeneralSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearing.
        /// </summary>
        internal static string HearingSettingHeader {
            get {
                return ResourceManager.GetString("HearingSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High contrast.
        /// </summary>
        internal static string HighContrastSettingName {
            get {
                return ResourceManager.GetString("HighContrastSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inking &amp; typing personalization.
        /// </summary>
        internal static string InkingAndTypingPersonalizationSettingName {
            get {
                return ResourceManager.GetString("InkingAndTypingPersonalizationSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        internal static string InteractionSettingHeader {
            get {
                return ResourceManager.GetString("InteractionSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string KeyboardSettingName {
            get {
                return ResourceManager.GetString("KeyboardSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageSettingName {
            get {
                return ResourceManager.GetString("LanguageSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationSettingName {
            get {
                return ResourceManager.GetString("LocationSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen.
        /// </summary>
        internal static string LockScreenSettingName {
            get {
                return ResourceManager.GetString("LockScreenSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier.
        /// </summary>
        internal static string MagnifierSettingName {
            get {
                return ResourceManager.GetString("MagnifierSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string MessagingSettingName {
            get {
                return ResourceManager.GetString("MessagingSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        internal static string MicrophoneSettingName {
            get {
                return ResourceManager.GetString("MicrophoneSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        internal static string MoreDetailsSettingName {
            get {
                return ResourceManager.GetString("MoreDetailsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        internal static string MouseSettingName {
            get {
                return ResourceManager.GetString("MouseSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multitasking.
        /// </summary>
        internal static string MultitaskingSettingName {
            get {
                return ResourceManager.GetString("MultitaskingSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrator.
        /// </summary>
        internal static string NarratorSettingName {
            get {
                return ResourceManager.GetString("NarratorSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi, airplane mode, VPN.
        /// </summary>
        internal static string NetworkAndInternetGroupDescription {
            get {
                return ResourceManager.GetString("NetworkAndInternetGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network &amp; Internet.
        /// </summary>
        internal static string NetworkAndInternetGroupName {
            get {
                return ResourceManager.GetString("NetworkAndInternetGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string NetworkStatusSettingName {
            get {
                return ResourceManager.GetString("NetworkStatusSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications &amp; actions.
        /// </summary>
        internal static string NotificationsAndActionsSettingName {
            get {
                return ResourceManager.GetString("NotificationsAndActionsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string NotificationsSettingName {
            get {
                return ResourceManager.GetString("NotificationsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline maps.
        /// </summary>
        internal static string OfflineMapsSettingName {
            get {
                return ResourceManager.GetString("OfflineMapsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other devices.
        /// </summary>
        internal static string OtherDevicesSettingName {
            get {
                return ResourceManager.GetString("OtherDevicesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen &amp; Windows Ink.
        /// </summary>
        internal static string PenAndWindowsInkSettingName {
            get {
                return ResourceManager.GetString("PenAndWindowsInkSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions &amp; History.
        /// </summary>
        internal static string PermissionsAndHistorySettingName {
            get {
                return ResourceManager.GetString("PermissionsAndHistorySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string PermissionsSettingName {
            get {
                return ResourceManager.GetString("PermissionsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background, lock screen, colors.
        /// </summary>
        internal static string PersonalizationGroupDescription {
            get {
                return ResourceManager.GetString("PersonalizationGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string PersonalizationGroupName {
            get {
                return ResourceManager.GetString("PersonalizationGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone calls.
        /// </summary>
        internal static string PhoneCallsSettingName {
            get {
                return ResourceManager.GetString("PhoneCallsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link your Android, iPhone.
        /// </summary>
        internal static string PhoneGroupDescription {
            get {
                return ResourceManager.GetString("PhoneGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneGroupName {
            get {
                return ResourceManager.GetString("PhoneGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string PicturesSettingName {
            get {
                return ResourceManager.GetString("PicturesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power &amp; sleep.
        /// </summary>
        internal static string PowerAndSleepSettingName {
            get {
                return ResourceManager.GetString("PowerAndSleepSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers &amp; scanners.
        /// </summary>
        internal static string PrintersAndScannersSettingName {
            get {
                return ResourceManager.GetString("PrintersAndScannersSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location, camera, microphone.
        /// </summary>
        internal static string PrivacyGroupDescription {
            get {
                return ResourceManager.GetString("PrivacyGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string PrivacyGroupName {
            get {
                return ResourceManager.GetString("PrivacyGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string PrivacySettingName {
            get {
                return ResourceManager.GetString("PrivacySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecting to this PC.
        /// </summary>
        internal static string ProjectingToThisPCSettingName {
            get {
                return ResourceManager.GetString("ProjectingToThisPCSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string ProxySettingName {
            get {
                return ResourceManager.GetString("ProxySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radios.
        /// </summary>
        internal static string RadiosSettingName {
            get {
                return ResourceManager.GetString("RadiosSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string RecoverySettingName {
            get {
                return ResourceManager.GetString("RecoverySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string RegionSettingName {
            get {
                return ResourceManager.GetString("RegionSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        internal static string RemoteDesktopSettingName {
            get {
                return ResourceManager.GetString("RemoteDesktopSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my files, permissions.
        /// </summary>
        internal static string SearchGroupDescription {
            get {
                return ResourceManager.GetString("SearchGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchGroupName {
            get {
                return ResourceManager.GetString("SearchGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching Windows.
        /// </summary>
        internal static string SearchingWindowsSettingName {
            get {
                return ResourceManager.GetString("SearchingWindowsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared experiences.
        /// </summary>
        internal static string SharedExperiencesSettingName {
            get {
                return ResourceManager.GetString("SharedExperiencesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in options.
        /// </summary>
        internal static string SignInOptionsSettingName {
            get {
                return ResourceManager.GetString("SignInOptionsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string SoundSettingName {
            get {
                return ResourceManager.GetString("SoundSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        internal static string SpeechSettingName {
            get {
                return ResourceManager.GetString("SpeechSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartSettingName {
            get {
                return ResourceManager.GetString("StartSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string StartupSettingName {
            get {
                return ResourceManager.GetString("StartupSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string StorageSettingName {
            get {
                return ResourceManager.GetString("StorageSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync your settings.
        /// </summary>
        internal static string SyncYourSettingsSettingName {
            get {
                return ResourceManager.GetString("SyncYourSettingsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display, sound, notifications, power.
        /// </summary>
        internal static string SystemGroupDescription {
            get {
                return ResourceManager.GetString("SystemGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemGroupName {
            get {
                return ResourceManager.GetString("SystemGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet mode.
        /// </summary>
        internal static string TabletModeSettingName {
            get {
                return ResourceManager.GetString("TabletModeSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Cortana.
        /// </summary>
        internal static string TalkToCortanaSettingName {
            get {
                return ResourceManager.GetString("TalkToCortanaSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar.
        /// </summary>
        internal static string TaskbarSettingName {
            get {
                return ResourceManager.GetString("TaskbarSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string TasksSettingName {
            get {
                return ResourceManager.GetString("TasksSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string ThemesSettingName {
            get {
                return ResourceManager.GetString("ThemesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech, region, date.
        /// </summary>
        internal static string TimeAndLanguageGroupDescription {
            get {
                return ResourceManager.GetString("TimeAndLanguageGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time &amp; Language.
        /// </summary>
        internal static string TimeAndLanguageGroupName {
            get {
                return ResourceManager.GetString("TimeAndLanguageGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        internal static string TroubleshootSettingName {
            get {
                return ResourceManager.GetString("TroubleshootSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing.
        /// </summary>
        internal static string TypingSettingName {
            get {
                return ResourceManager.GetString("TypingSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update, recovery, backup.
        /// </summary>
        internal static string UpdateAndSecurityGroupDescription {
            get {
                return ResourceManager.GetString("UpdateAndSecurityGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &amp; Security.
        /// </summary>
        internal static string UpdateAndSecurityGroupName {
            get {
                return ResourceManager.GetString("UpdateAndSecurityGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB.
        /// </summary>
        internal static string UsbSettingName {
            get {
                return ResourceManager.GetString("UsbSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video playback.
        /// </summary>
        internal static string VideoPlaybackSettingName {
            get {
                return ResourceManager.GetString("VideoPlaybackSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string VideosSettingName {
            get {
                return ResourceManager.GetString("VideosSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        internal static string VisionSettingHeader {
            get {
                return ResourceManager.GetString("VisionSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice activation.
        /// </summary>
        internal static string VoiceActivationSettingName {
            get {
                return ResourceManager.GetString("VoiceActivationSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN.
        /// </summary>
        internal static string VpnSettingName {
            get {
                return ResourceManager.GetString("VpnSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Insider Program.
        /// </summary>
        internal static string WindowsInsiderProgramSettingName {
            get {
                return ResourceManager.GetString("WindowsInsiderProgramSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows permissions.
        /// </summary>
        internal static string WindowsPermissionsSettingHeader {
            get {
                return ResourceManager.GetString("WindowsPermissionsSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Security.
        /// </summary>
        internal static string WindowsSecuritySettingName {
            get {
                return ResourceManager.GetString("WindowsSecuritySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update.
        /// </summary>
        internal static string WindowsUpdateSettingName {
            get {
                return ResourceManager.GetString("WindowsUpdateSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Networking.
        /// </summary>
        internal static string XboxNetworkingSettingName {
            get {
                return ResourceManager.GetString("XboxNetworkingSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your info.
        /// </summary>
        internal static string YourInfoSettingName {
            get {
                return ResourceManager.GetString("YourInfoSettingName", resourceCulture);
            }
        }
    }
}
