//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsSettingsClone.Uwp.ViewModels {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsSettingsClone.Uwp.ViewModels.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutSettingName {
            get {
                return ResourceManager.GetString("AboutSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your accounts, email, sync, work, family.
        /// </summary>
        internal static string AccountsGroupDescription {
            get {
                return ResourceManager.GetString("AccountsGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string AccountsGroupName {
            get {
                return ResourceManager.GetString("AccountsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall, defaults, optional features.
        /// </summary>
        internal static string AppsGroupDescription {
            get {
                return ResourceManager.GetString("AppsGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string AppsGroupName {
            get {
                return ResourceManager.GetString("AppsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string ClipboardSettingName {
            get {
                return ResourceManager.GetString("ClipboardSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortana language, permissions, notifications.
        /// </summary>
        internal static string CortanaGroupDescription {
            get {
                return ResourceManager.GetString("CortanaGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortana.
        /// </summary>
        internal static string CortanaGroupName {
            get {
                return ResourceManager.GetString("CortanaGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth, printers, mouse.
        /// </summary>
        internal static string DevicesGroupDescription {
            get {
                return ResourceManager.GetString("DevicesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string DevicesGroupName {
            get {
                return ResourceManager.GetString("DevicesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string DisplaySettingName {
            get {
                return ResourceManager.GetString("DisplaySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrator, magnifier, high contrast.
        /// </summary>
        internal static string EaseOfAccessGroupDescription {
            get {
                return ResourceManager.GetString("EaseOfAccessGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of Access.
        /// </summary>
        internal static string EaseOfAccessGroupName {
            get {
                return ResourceManager.GetString("EaseOfAccessGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus assist.
        /// </summary>
        internal static string FocusAssistSettingName {
            get {
                return ResourceManager.GetString("FocusAssistSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game bar, captures, broadcasting, Game Mode.
        /// </summary>
        internal static string GamingGroupDescription {
            get {
                return ResourceManager.GetString("GamingGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming.
        /// </summary>
        internal static string GamingGroupName {
            get {
                return ResourceManager.GetString("GamingGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multitasking.
        /// </summary>
        internal static string MultitaskingSettingName {
            get {
                return ResourceManager.GetString("MultitaskingSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi, airplane mode, VPN.
        /// </summary>
        internal static string NetworkAndInternetGroupDescription {
            get {
                return ResourceManager.GetString("NetworkAndInternetGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network &amp; Internet.
        /// </summary>
        internal static string NetworkAndInternetGroupName {
            get {
                return ResourceManager.GetString("NetworkAndInternetGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications &amp; actions.
        /// </summary>
        internal static string NotificationsAndActionsSettingName {
            get {
                return ResourceManager.GetString("NotificationsAndActionsSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background, lock screen, colors.
        /// </summary>
        internal static string PersonalizationGroupDescription {
            get {
                return ResourceManager.GetString("PersonalizationGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string PersonalizationGroupName {
            get {
                return ResourceManager.GetString("PersonalizationGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link your Android, iPhone.
        /// </summary>
        internal static string PhoneGroupDescription {
            get {
                return ResourceManager.GetString("PhoneGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneGroupName {
            get {
                return ResourceManager.GetString("PhoneGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power &amp; sleep.
        /// </summary>
        internal static string PowerAndSleepSettingName {
            get {
                return ResourceManager.GetString("PowerAndSleepSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location, camera, microphone.
        /// </summary>
        internal static string PrivacyGroupDescription {
            get {
                return ResourceManager.GetString("PrivacyGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string PrivacyGroupName {
            get {
                return ResourceManager.GetString("PrivacyGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecting to this PC.
        /// </summary>
        internal static string ProjectingToThisPCSettingName {
            get {
                return ResourceManager.GetString("ProjectingToThisPCSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        internal static string RemoteDesktopSettingName {
            get {
                return ResourceManager.GetString("RemoteDesktopSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my files, permissions.
        /// </summary>
        internal static string SearchGroupDescription {
            get {
                return ResourceManager.GetString("SearchGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchGroupName {
            get {
                return ResourceManager.GetString("SearchGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared experiences.
        /// </summary>
        internal static string SharedExperiencesSettingName {
            get {
                return ResourceManager.GetString("SharedExperiencesSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string SoundSettingName {
            get {
                return ResourceManager.GetString("SoundSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string StorageSettingName {
            get {
                return ResourceManager.GetString("StorageSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display, sound, notifications, power.
        /// </summary>
        internal static string SystemGroupDescription {
            get {
                return ResourceManager.GetString("SystemGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemGroupName {
            get {
                return ResourceManager.GetString("SystemGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet mode.
        /// </summary>
        internal static string TabletModeSettingName {
            get {
                return ResourceManager.GetString("TabletModeSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech, region, date.
        /// </summary>
        internal static string TimeAndLanguageGroupDescription {
            get {
                return ResourceManager.GetString("TimeAndLanguageGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time &amp; Language.
        /// </summary>
        internal static string TimeAndLanguageGroupName {
            get {
                return ResourceManager.GetString("TimeAndLanguageGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update, recovery, backup.
        /// </summary>
        internal static string UpdateAndSecurityGroupDescription {
            get {
                return ResourceManager.GetString("UpdateAndSecurityGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &amp; Security.
        /// </summary>
        internal static string UpdateAndSecurityGroupName {
            get {
                return ResourceManager.GetString("UpdateAndSecurityGroupName", resourceCulture);
            }
        }
    }
}
